### ISSUE TITLE
unknown command:'load_plugin'

### ISSUE THREAD

**Issue by nemare** [sycurelab/DECAF#36]
I installed Qemu1.0 and DECAF1.9 on my ubuntu 12.04.
I  converted a vmdk image to qcow2 format by: qemu-img convert win7.vmdk -O qcow win7.img. 
And started it by:  ./qemu-­system­-i386 -­monitor stdio -­m 512 ­-netdev user,id=mynet -­device rtl8139,netdev=mynet  win7.img. 
Windows 7 started but when i tried to load a plugin by:load_plugin .It said unknown command, as follow.
I followed https://code.google.com/archive/p/decaf-platform/wikis/build_conf.wiki to install qemu and decaf.Both Windows 7 and Ubuntu are 32bit.
What's the problem?
![img_1611](https://cloud.githubusercontent.com/assets/6057260/14169432/454f9236-f75a-11e5-8dbf-ae531676a8e7.JPG)

**Comment by hengyin** [comment]
It looks to me that you are somehow running the original QEMU, not DECAF. All DECAF-specific commands are not shown in the screenshot.

**Comment by nemare** [comment]
thank you very much for your quick answer!
