### ISSUE TITLE
About address of instruction

### ISSUE THREAD

**Issue by nemare** [sycurelab/DECAF#37]
Hello:
   May I ask how to get address of instructions like Pin does with  INS_Address(ins) ?
Thanks!

**Comment by hengyin** [comment]
If you just want to get the address of the current instruction, you can use
DECAF_getPC().

Heng

**Comment by nemare** [comment]
Thank you for your answer! Is DECAF_getPC() the same as params->ib.env->eip in INSN_BEGIN_CB? I found it that they print the same result?

**Comment by hengyin** [comment]
Yes.
