### ISSUE TITLE
problem in running emulator commond in DroidScope

### ISSUE THREAD

**Issue by hkxicor** [sycurelab/DECAF#43]
daya@Vostro-ubunu:~/tdroid/tdroid-4.3_r1/external/DroidScope/objs$ ./emulator -sysdir /home/daya/tdroid/tdroid-4.3_r1/out/target/product/generic/ -kernel /home/daya/ -memory 512 -qemu -monitor stdio
emulator: WARNING: system partition size adjusted to match image file (238 MB > 200 MB)

Failed to load libGL.so
error libGL.so: cannot open shared object file: No such file or directory
Failed to load libGL.so
error libGL.so: cannot open shared object file: No such file or directory
qemu: could not load kernel '/home/daya/'

**Comment by yueduan** [comment]
hi,

"-kernel /home/daya/"

mostly likely you didn't specify the kernel path correctly. Please make sure you have kernel image under the /home/daya/ directory.
